-- STATION DATA
INSERT INTO station VALUES (1, 'NEW DELHI', 'DELHI');
INSERT INTO station VALUES (2, 'MUMBAI CENTRAL', 'MUMBAI');

-- TRAIN DATA
INSERT INTO train VALUES (101, 'RAJDHANI EXPRESS', 1, 2, 2);

-- PASSENGER DATA
INSERT INTO passenger VALUES (201, 'RAJU', 25, 'MALE');
INSERT INTO passenger VALUES (202, 'SUNITA', 32, 'FEMALE');

COMMIT;
